# Generated by Django 3.2.12 on 2023-12-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='counted_view',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
    ]
