# Generated by Django 3.2.23 on 2023-12-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_counted_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='counted_view',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
